//
//	Author: A.L. Hertog
//	Date: 19 Juni 2009
//	License: GPL
//
//

#ifndef FIELDSPINEDITWIDGETGTKMM_H
#define FIELDSPINEDITWIDGETGTKMM_H



#include "Category.h"
#include "Field.h"
#include "SpinField.h"
#include "FieldEditWidgetGTKMM.h"
#include "YesNoToggleButtonGTKMM.h"

#include <gtkmm.h>

#include <iostream>
#include <string>
using namespace std;


//! This class represents a window in which the properties of a spin field can be edited.

class FieldSpinEditWidgetGTKMM : public FieldEditWidgetGTKMM
{

	public:
	
		FieldSpinEditWidgetGTKMM( Field* pField, int i );
		~FieldSpinEditWidgetGTKMM();


	private:
	
		Gtk::Label labelMax, labelMin, labelStepsize, labelAdhereStep, labelDec, labelAlwaysUpdate;
		Gtk::CheckButton checkMax, checkMin;
		Gtk::SpinButton spinMax, spinMin, spinStepsize, spinDec;
		YesNoToggleButtonGTKMM toggleAdhereStep, toggleAlwaysUpdate;
		Gtk::HBox hBoxMax, hBoxMin;
		
		// Pointer to the baseField but of different type for easy acces to specific funcitons.
		SpinField* spinField;
		
		// Functions to handle signals generated by the buttons.
		void changeMax( );
		void changeMin( );
		void activateMax( );
		void activateMin( );
		void changeStepsize( );
		void changeDec( );
		void changeAdhereStep( );
		void changeAlwaysUpdate( );


};



#endif
