//
//	Author: A.L. Hertog
//	Date: 9 April 2009
//	Copyrights Pluton IT B.V. http://www.pluton.nl
//	License: GPL-v2
//
//

#include "FieldTableGTKMM.h"

#include <iostream>

//-----------------------------------------------------------------------------

FieldTableGTKMM::FieldTableGTKMM()
{

#ifdef DEBUG_MESSAGES_DEF
	cout << "Constructing FieldTableGTKMM	object.\n";
#endif

	objectData = NULL;

	this->set_homogeneous(false);
	this->show();
	this->set_child_visible();	

};

//-----------------------------------------------------------------------------

FieldTableGTKMM::~FieldTableGTKMM()
{
#ifdef DEBUG_MESSAGES_DEF
	cout << "Destroyed a FieldTableGTKMM object.\n";
#endif
};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::addField( Gtk::Widget* field )
{
	this->pack_start( *field,	false, false, 2 );
};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::deleteField( int index )
{

#ifdef TODO_DEF
#warning TODO in file __FILE__ at line __LINE__.
#endif

};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::makeNewTable( Category* category )
{

	FieldGTKMM* fieldGTKMM = NULL;
	int size = category->getFieldsSize();
	Field* field = NULL;
	
	// Disconnect excisting signals
	for( int i = 0; i < connections.size(); i++ )
	{
		connections[i].disconnect();
	};	
	connections.clear();

	
	for( int i = 0; i < size; i++ )
	{
		field = category->getFieldAt( i );
		fieldGTKMM = new FieldGTKMM( field, i );
		
	
		this->addField( (Gtk::Widget*)fieldGTKMM );
		
		// Create the connection the the childs signal and add the connection to the vector.
		connections.push_back( (fieldGTKMM->get_signal_selected()).connect( sigc::mem_fun(this, &FieldTableGTKMM::fieldSelected) ) );
	}
	
	this->show_all();
	
};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::makeNewTable( ObjectData* object )
{
#ifdef TODO_DEF
#warning TODO in file __FILE__ at line __LINE__.
#endif
};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::fillTable( ObjectData* object )
{
#ifdef TODO_DEF
#warning TODO in file __FILE__ at line __LINE__.
#endif
};



//-----------------------------------------------------------------------------


void FieldTableGTKMM::clear(  )
{
#ifdef TODO_DEF
#warning TODO in file __FILE__ at line __LINE__.
#endif
};

//-----------------------------------------------------------------------------

void FieldTableGTKMM::fieldSelected( int fieldIndex )
{
	// Pass the signal generated by the Field on to the EngineGTKMM.
	signal_selectionChange.emit( fieldIndex );
};

//-----------------------------------------------------------------------------

FieldTableGTKMM::type_signal_selectionChange FieldTableGTKMM::get_signal_selectionChange( void )
{
	return signal_selectionChange;
};

//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------

