Project: FieldException Class Reference
FieldException Class Reference
A class which defines exceptions which can occur during operations in the field class and its children.
#include <FieldException.h>
Public Member Functions
FieldException (int errorNumber)
The constructor.
FieldException (int errorNumber, string type, string label)
FieldException (int errorNumber, string type, string label, string info)
FieldException (const FieldException &fieldEx)
A copy constructor.
~FieldException () throw ()
The destructor.
void setFieldType (string type)
Set function for the field type.
void setFieldLabel (string label)
Set function for the field label.
void addInfo (const string &info)
Add additional information.
Detailed Description
A class which defines exceptions which can occur during operations in the field class and its children.
Definition at line 21 of file FieldException.h.
Constructor & Destructor Documentation
FieldException::FieldException (int errorNumber)
The constructor.
Parameters:
errorNumber is the index number of error which caused this exception.
See also:
FieldException::errorString[]
Definition at line 25 of file FieldException.cpp.
FieldException::FieldException (int errorNumber, string type, string label)
Parameters:
errorNumber is the index number of error which caused this exception.
type the type of field in which the exception occurred.
label the label of the specific field.
Definition at line 36 of file FieldException.cpp.
FieldException::FieldException (int errorNumber, string type, string label, string info)
Parameters:
errorNumber is the index number of error which caused this exception.
type the type of field in which the exception occurred.
label the label of the specific field.
info additional information about the error.
Definition at line 49 of file FieldException.cpp.
Member Function Documentation
void FieldException::setFieldType (string type)
Set function for the field type.
Use this function to set the type of field in which this exception occurred.
Definition at line 82 of file FieldException.cpp.
Referenced by CheckField::CheckField(), ComboField::ComboField(), SpinField::SpinField(), and TextField::TextField().
void FieldException::setFieldLabel (string label)
Set function for the field label.
Use this function to set the field label. This to be able to identify the field in which this exception occurred.
Definition at line 91 of file FieldException.cpp.
Referenced by CheckField::CheckField(), ComboField::ComboField(), SpinField::SpinField(), and TextField::TextField().
void FieldException::addInfo (const string & info)
Add additional information.
Add additional information to this exception. For example one can use this function to add the file name and line number of the category file which was been processed.
Definition at line 144 of file FieldException.cpp.
Referenced by CheckField::CheckField(), ComboField::ComboField(), Category::loadCategory(), SpinField::SpinField(), and TextField::TextField().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/FieldException.h
/home/bart/DMS/src/Category/FieldException.cpp