Project: TextField Class Reference
TextField Class Reference
A child class of Field defining a text field.
#include <TextField.h>
Public Member Functions
TextField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
TextField (vector< string > *description)
A Construct which creates a TextField from a description.
~TextField ()
The destructor.
string getType ()
Get function, the implementation of the virtual function in the Field class.
Detailed Description
A child class of Field defining a text field.
Definition at line 12 of file TextField.h.
Constructor & Destructor Documentation
TextField::TextField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
See also:
Field::Field()
Definition at line 19 of file TextField.cpp.
TextField::TextField (vector< string > * description)
A Construct which creates a TextField from a description.
This constructor is used by Field::newField(vector<string> * description)
Parameters:
description vector containing strings from a category definition file
Definition at line 28 of file TextField.cpp.
References FieldException::addInfo(), Field::getLabel(), getType(), FieldException::setFieldLabel(), FieldException::setFieldType(), Field::setLabel(), Field::setRequired(), Field::setReset(), and Field::stringToBool().
Member Function Documentation
string TextField::getType () [virtual]
Get function, the implementation of the virtual function in the Field class.
See also:
Field::getType()
Returns:
The type of this field: TextField.
Reimplemented from Field.
Definition at line 94 of file TextField.cpp.
Referenced by TextField().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/TextField.h
/home/bart/DMS/src/Category/TextField.cpp