Project: Field Class Reference
Field Class Reference
A class which defines the basic information about a categorisation field.
#include <Field.h>
Public Member Functions
Field ()
The default constructor.
Field (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor with parameters.
~Field ()
The destructor.
virtual string getType ()
A virtual function to get the type of field.
virtual vector< string > getDescription ()
A virtual function to get a full description of the field with all its options.
string getLabel ()
A function which returns the field type.
bool getRequired ()
A get function for required.
bool getReset ()
A get function for reset.
void setLabel (string fieldLabel)
A set function for label.
void setRequired (bool fieldRequired)
A set function for required .
void setReset (bool fieldReset)
A set function for reset.
Static Public Member Functions
static Field * newField (vector< string > *description)
A function to create a new Field object or one of its childeren.
Protected Member Functions
bool stringToBool (string input)
A function to convert strings to booleans.
string boolToString (bool input)
A function to convert booleans to strings.
double stringToDouble (string input)
Converts a string to a double.
string doubleToString (double input)
Converts a double to a string.
Detailed Description
A class which defines the basic information about a categorisation field.
Definition at line 20 of file Field.h.
Constructor & Destructor Documentation
Field::Field (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor with parameters.
Parameters:
fieldLabel is a description of the field which is presented to the user via the UI.
fieldRequired indicates if the user is required to fill in this field.
fieldReset indicates whether the contents of this field is deleted when continuing with the next item.
Definition at line 33 of file Field.cpp.
Member Function Documentation
string Field::getType () [virtual]
A virtual function to get the type of field.
Returns:
A string is returned which contains the field type.
Reimplemented in CheckField, ComboField, SpinField, and TextField.
Definition at line 107 of file Field.cpp.
Referenced by getDescription().
vector< string > Field::getDescription () [virtual]
A virtual function to get a full description of the field with all its options.
This function returns information about this field. This can be used to generate a category definition file.
Returns:
A pointer to a vector of strings. These strings contain all information of this field: type, label, required, reset and any additional information implemented in the child of this class.
Reimplemented in ComboField, and SpinField.
Definition at line 115 of file Field.cpp.
References boolToString(), getLabel(), and getType().
string Field::getLabel ()
A function which returns the field type.
Returns:
A string is returned containing the field type.
Definition at line 136 of file Field.cpp.
Referenced by CheckField::CheckField(), ComboField::ComboField(), SpinField::getDescription(), getDescription(), ComboField::getDescription(), SpinField::SpinField(), and TextField::TextField().
bool Field::getRequired ()
A get function for required.
Returns:
A boolean which indicates whether or not the user is required to fill in this field.
Definition at line 145 of file Field.cpp.
Referenced by SpinField::getDescription(), and ComboField::getDescription().
bool Field::getReset ()
A get function for reset.
Returns:
A boolean which indicates whether the contents of this field is deleted when continuing with the next item.
Definition at line 153 of file Field.cpp.
Referenced by SpinField::getDescription(), and ComboField::getDescription().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/Field.h
/home/bart/DMS/src/Category/Field.cpp