Project: CheckField Class Reference
CheckField Class Reference
A child class of Field defining a check field.
#include <CheckField.h>
Public Member Functions
CheckField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
CheckField (vector< string > *description)
A Construct which creates a CheckField from a description.
~CheckField ()
The destructor.
string getType ()
Get function.
Detailed Description
A child class of Field defining a check field.
Definition at line 16 of file CheckField.h.
Constructor & Destructor Documentation
CheckField::CheckField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
See also:
Field::Field()
Definition at line 18 of file CheckField.cpp.
CheckField::CheckField (vector< string > * description)
A Construct which creates a CheckField from a description.
This constructor is used by Field::newField(vector<string> * description)
Parameters:
description vector containing strings from a category definition file
Definition at line 27 of file CheckField.cpp.
References FieldException::addInfo(), Field::getLabel(), getType(), FieldException::setFieldLabel(), FieldException::setFieldType(), Field::setLabel(), Field::setRequired(), Field::setReset(), and Field::stringToBool().
Member Function Documentation
string CheckField::getType () [virtual]
Get function.
Returns:
The type of this field: CheckField.
Reimplemented from Field.
Definition at line 93 of file CheckField.cpp.
Referenced by CheckField().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/CheckField.h
/home/bart/DMS/src/Category/CheckField.cpp