Project: SpinField Class Reference
SpinField Class Reference
A class which defines a spin field.
#include <SpinField.h>
Public Member Functions
SpinField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
SpinField (string fieldLabel, bool fieldRequired, bool fieldReset, double *minimum, double *maximum, double stepsize, bool adStep, int decimals, bool adDec)
Expanded constructor.
SpinField (vector< string > *description)
A Construct which creates a SpinField from a description.
~SpinField ()
The destructor.
string getType ()
Get function for the type.
vector< string > getDescription ()
A virtual function to get a full description of the field with all its options.
double * getMaximum ()
Returns a pointer to the lowest possible value of the spin field. NULL means that there is no limit to this value.
double getStepsize ()
Returns a pointer to the highest possible value of the spin field. NULL means that there is no limit to this value.
bool getAdhereStep ()
Returns the increment size of the field.
int getDecimals ()
Indicates whether or not manually entered values are rounded of to the nearest multiplication of the step size. Thus TRUE when rounding of.
bool getAdhereDec ()
Returns the number of decimals displayed in the field.
void setMinimum (double *minimum)
Indicates whether manually entered values are displayed according to the number of decimals displayed. If FALSE the fully entered value is displayed.
void setMaximum (double *maximum)
Set the lowest possible value of the spin field. Set it equal to NULL to indicate that there is no limit.
void setStepsize (double stepsize)
Set the highest possible value of the spin field. Set it equal to NULL to indicate that there is no limit.
void setAdhereStep (bool adhere)
Set the increment size of the spin field. This value should not be equal to zero unless adhereStep is FALSE, in this way only manual entries are possible.
void setDecimals (int decimals)
Indicated if manually entered values are rounded to the nearest multiplication of the step size.
void setAdhereDec (bool adhere)
Set the number of displayed decimals.
Detailed Description
A class which defines a spin field.
Definition at line 15 of file SpinField.h.
Constructor & Destructor Documentation
SpinField::SpinField (string fieldLabel, bool fieldRequired, bool fieldReset)
The constructor.
See also:
Field::Field()
Definition at line 20 of file SpinField.cpp.
SpinField::SpinField (vector< string > * description)
A Construct which creates a SpinField from a description.
This constructor is used by Field::newField(vector<string> * description)
Parameters:
description vector containing strings from a category definition file
Definition at line 82 of file SpinField.cpp.
References FieldException::addInfo(), Field::getLabel(), getType(), FieldException::setFieldLabel(), FieldException::setFieldType(), Field::setLabel(), Field::setRequired(), Field::setReset(), and Field::stringToBool().
Member Function Documentation
string SpinField::getType () [virtual]
Get function for the type.
Returns:
The type of this field: SpinField.
Reimplemented from Field.
Definition at line 171 of file SpinField.cpp.
Referenced by getDescription(), and SpinField().
vector< string > SpinField::getDescription () [virtual]
A virtual function to get a full description of the field with all its options.
This function returns information about this field. This can be used to generate a category definition file.
Returns:
A pointer to a vector of strings. These strings contain all information of this field: type, label, required, reset, min, max, step, adhereStep, dec, adhereDec.
Reimplemented from Field.
Definition at line 179 of file SpinField.cpp.
References Field::boolToString(), getAdhereDec(), getAdhereStep(), getDecimals(), Field::getLabel(), getMaximum(), Field::getRequired(), Field::getReset(), getStepsize(), and getType().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/SpinField.h
/home/bart/DMS/src/Category/SpinField.cpp