Project: ComboField Class Reference
ComboField Class Reference
A child class of Field defining a check field.
#include <ComboField.h>
Public Member Functions
ComboField (string fieldLabel, bool fieldRequired, bool fieldReset, vector< string > *fieldCombo, ComboType fieldType)
The constructor.
ComboField (vector< string > *description)
A Construct which creates a ComboField from a description.
~ComboField ()
The destructor.
string getType ()
Get function.
vector< string > getDescription ()
A virtual function to get a full description of the field with all its options.
int getComboSize ()
Get function for the size of the combo vector.
string getComboElement (int n)
Get function to obtain an element from the combo vector.
Detailed Description
A child class of Field defining a check field.
Definition at line 23 of file ComboField.h.
Constructor & Destructor Documentation
ComboField::ComboField (string fieldLabel, bool fieldRequired, bool fieldReset, vector< string > * fieldCombo, ComboType fieldType)
The constructor.
See also:
Field::Field()
Parameters:
fieldCobo an array with different combo options.
fieldType defines the different types of field combos: Combo, ComboEntry, ComboRadio.
Definition at line 19 of file ComboField.cpp.
ComboField::ComboField (vector< string > * description)
A Construct which creates a ComboField from a description.
This constructor is used by Field::newField(vector<string> * description)
Parameters:
description vector containing strings from a category definition file
Definition at line 29 of file ComboField.cpp.
References FieldException::addInfo(), Field::getLabel(), getType(), FieldException::setFieldLabel(), FieldException::setFieldType(), Field::setLabel(), Field::setRequired(), Field::setReset(), and Field::stringToBool().
Member Function Documentation
string ComboField::getType () [virtual]
Get function.
Returns:
The type of this field: 0 = "ComboField", 1 = "ComboEntryField", 2 = "ComboRadioField".
Reimplemented from Field.
Definition at line 144 of file ComboField.cpp.
Referenced by ComboField(), and getDescription().
vector< string > ComboField::getDescription () [virtual]
A virtual function to get a full description of the field with all its options.
This function returns information about this field. This can be used to generate a category definition file.
Returns:
A pointer to a vector of strings. These strings contain all information of this field: type, label, required, reset, the number of combo elements and all combo elements.
Reimplemented from Field.
Definition at line 163 of file ComboField.cpp.
References Field::boolToString(), getComboElement(), getComboSize(), Field::getLabel(), Field::getRequired(), Field::getReset(), and getType().
int ComboField::getComboSize ()
Get function for the size of the combo vector.
Returns:
This function returns an integer containing the number of elements in the combo vector.
Definition at line 196 of file ComboField.cpp.
Referenced by getDescription().
string ComboField::getComboElement (int n)
Get function to obtain an element from the combo vector.
Parameters:
n is the index number of the desired element starting from 0.
Returns:
A string is returend containing the contents element n. An empty string, "", is returned when n is out of range.
Definition at line 205 of file ComboField.cpp.
Referenced by getDescription().
The documentation for this class was generated from the following files:
/home/bart/DMS/src/Category/ComboField.h
/home/bart/DMS/src/Category/ComboField.cpp